name: Node.js CI

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master", "dev" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      # 1. Récupération du code source
      - name: Checkout du code
        uses: actions/checkout@v4

      # 2. Configuration de l'environnement Node.js (Node 22)
      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      # 3. Installation des dépendances
      - name: Installation des dépendances
        run: npm install

      # 4. Exécution des tests Jest
      - name: Exécution des tests backend
        run: npm test